# Generated by Django 2.1.3 on 2018-11-03 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=70)),
                ('easting', models.DecimalField(decimal_places=4, max_digits=10)),
                ('northing', models.DecimalField(decimal_places=4, max_digits=10)),
                ('elevation', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Instrument information',
            },
        ),
        migrations.CreateModel(
            name='InstrumentReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateTimeField()),
                ('reading', models.DecimalField(decimal_places=4, max_digits=14)),
                ('instrument_id', models.ForeignKey(db_column='instrument_name', on_delete=django.db.models.deletion.CASCADE, to='instruments.InstrumentInformation')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_type', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='instrumentinformation',
            name='instrument_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.InstrumentType'),
        ),
    ]
