# Generated by Django 2.1.3 on 2018-11-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentinformation',
            name='easting',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='instrumentinformation',
            name='northing',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
    ]
